---
train:
  - learning_rate: 0.00001
  - max_epochs: 300
  - model_name: unet
  - num_workers: 10
  - percentage_train: 0.8
  - seed: 1
  - save_path: unet_no_centre_1

sdnet:
  - model_params:
      - width: 512
      - height: 512
      - ndf: 64
      - norm: batchnorm
      - upsample: nearest
      - num_classes: 1
      - num_mask_channels: 8
      - anatomy_out_channels: 8
  - lightning:
      - charbonnier: 0
      - dice_w: 10
      - focal_w: 0
      - kl_w: 0.01
      - z_length: 8
      - reco_w: 1
      - regress_w: 1
      - weight_init: xavier

classifier:
  - num_classes: 5
  - resnet_version: 50
  - transfer: True
  - fine_tuning: False

unet:
  - n_channels: 3
  - num_classes: 2
  - bilinear: True

wandb:
  - project_name: gradcam_deeplab_miccai
  - wandb_name: gradcam_deeplab_all_centres_60perc

defaults:
  - dataset: baseline
